/**
 * HTTP helpers for the operator routes: domain-error mapping, JSON views
 * (bigints as base-unit strings), owner checks and single-flight per event.
 */
import type { Context } from "hono";
import { SettleKitError } from "@settlekit/common";
import {
  BillValidationError,
  DuplicateEventError,
  EscalationStateError,
  EventValidationError,
  OperatorServiceError,
  PolicyDriftError,
  PolicyValidationError,
  X402Error,
} from "@settlekit/operator";
import type { AppEnv } from "../context.js";

/** Render bigints as base-unit decimal strings so bodies are JSON-safe. */
export function jsonView(value: unknown): unknown {
  if (typeof value === "bigint") return value.toString();
  if (Array.isArray(value)) return value.map(jsonView);
  if (value !== null && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, jsonView(v)]));
  }
  return value;
}

/** Map operator domain errors onto SettleKitError with the right status. */
export function toHttpError(err: unknown): unknown {
  if (err instanceof EventValidationError || err instanceof BillValidationError || err instanceof PolicyValidationError) {
    return new SettleKitError({ code: "validation_error", message: err.message, httpStatus: 400, details: { issues: [...err.issues] } });
  }
  if (err instanceof PolicyDriftError) {
    return new SettleKitError({ code: "conflict", message: err.message, httpStatus: 409, details: { drift: [...err.issues] } });
  }
  if (err instanceof DuplicateEventError) {
    return new SettleKitError({ code: "conflict", message: err.message, httpStatus: 409 });
  }
  if (err instanceof EscalationStateError || err instanceof X402Error) {
    return new SettleKitError({ code: "conflict", message: err.message, httpStatus: 409 });
  }
  if (err instanceof OperatorServiceError) {
    const notFound = /not found/.test(err.message);
    return new SettleKitError({ code: notFound ? "not_found" : "conflict", message: err.message, httpStatus: notFound ? 404 : 409 });
  }
  return err;
}

export function forbidden(message: string): SettleKitError {
  return new SettleKitError({ code: "forbidden", message, httpStatus: 403 });
}

export function notFound(message: string): SettleKitError {
  return new SettleKitError({ code: "not_found", message, httpStatus: 404 });
}

/**
 * Owner credentials: the bootstrap key, a first-party dashboard session (a
 * human), or an API key id listed in OPERATOR_OWNER_KEY_IDS. Programmatic
 * agent keys can submit events but never change policy or resolve escalations.
 * `apiKeyId` is set only by the auth middleware ("bootstrap" for the env
 * bootstrap key, "session:<accountId>" for verified sessions); stored API key
 * ids are generated by @settlekit/api-keys and never use either form.
 */
export function isOwner(c: Context<AppEnv>, env: NodeJS.ProcessEnv = process.env): boolean {
  const keyId = c.get("apiKeyId");
  if (!keyId) return false;
  if (keyId === "bootstrap" || keyId.startsWith("session:")) return true;
  const owners = (env.OPERATOR_OWNER_KEY_IDS ?? "").split(",").map((s) => s.trim()).filter(Boolean);
  return owners.includes(keyId);
}

export function ownerId(c: Context<AppEnv>): string {
  return c.get("apiKeyId") ?? "unknown";
}

/** Run at most one handler per key at a time within this process. */
export class SingleFlight {
  private inFlight: ReadonlyMap<string, Promise<unknown>> = new Map();

  async run<T>(key: string, work: () => Promise<T>): Promise<T> {
    const existing = this.inFlight.get(key);
    if (existing) return existing as Promise<T>;
    const promise = work().finally(() => {
      this.inFlight = new Map([...this.inFlight].filter(([k]) => k !== key));
    });
    this.inFlight = new Map([...this.inFlight, [key, promise]]);
    return promise;
  }
}

/** Tiny TTL cache for public aggregates. */
export class TtlCache<T> {
  private entry: { readonly at: number; readonly value: Promise<T> } | null = null;

  constructor(private readonly ttlMs: number, private readonly now: () => number = Date.now) {}

  get(load: () => Promise<T>): Promise<T> {
    const t = this.now();
    if (this.entry && t - this.entry.at < this.ttlMs) return this.entry.value;
    const value = load().catch((error: unknown) => {
      this.entry = null;
      throw error;
    });
    this.entry = { at: t, value };
    return value;
  }
}
