/**
 * Delivery materialization.
 *
 * Given a confirmed payment + the product's delivery action + the buyer's
 * collected fields, produce the concrete access artifacts shown on the success
 * page. Every artifact is generated by a real @settlekit package function:
 *
 *  - license keys  -> @settlekit/license-keys createLicenseKey
 *  - api keys      -> @settlekit/api-keys issueApiKey
 *  - file download -> @settlekit/file-delivery generateSignedDownloadUrl
 *  - github access -> the REAL GitHub App invite run once by ./fulfill; this
 *                     module only renders its stored outcome (active invite
 *                     or pending) and never fabricates an invite link
 *  - discord role  -> the REAL bot role grant run once by ./fulfill; rendered
 *                     from its stored outcome (granted or pending), never faked
 *
 * These run server-side and are deterministic for a given session (so the
 * success page is stable on refresh): we derive entitlement ids and tokens
 * from the payment id rather than minting fresh random ids each render.
 */
import { createHmac } from "node:crypto";
import { createLicenseKey } from "@settlekit/license-keys";
import { issueApiKey } from "@settlekit/api-keys";
import { generateSignedDownloadUrl } from "@settlekit/file-delivery";
import type { DeliveryAction, Entitlement, Payment, Product } from "@settlekit/common";

import { resolveRepoTarget } from "./github-delivery";
import { DEMO_DOWNLOAD_BASE, DEMO_ORG, DEMO_SECRET } from "./seed";
import type { DeliveredAccess } from "./types";

/** Deterministic pseudo-id derived from a seed so renders are stable. */
function derivedId(prefix: string, seed: string): string {
  const hex = createHmac("sha256", DEMO_SECRET)
    .update(seed)
    .digest("hex")
    .slice(0, 24);
  return `${prefix}_${hex}`;
}

/** The entitlement id fulfillment stores for a payment (stable per payment). */
export function entitlementIdForPayment(payment: Payment): string {
  return derivedId("ent", payment.id);
}

/** Stored fulfillment state the GitHub artifacts are rendered from. */
export interface FulfillmentState {
  /** The payment's entitlement, once fulfillment has run. */
  entitlement?: Entitlement;
  /** Whether a GitHub App is configured on this deployment. */
  githubReady: boolean;
  /** Whether the Discord bot is configured on this deployment. */
  discordReady?: boolean;
}

/**
 * Build the delivered access list for a confirmed payment. Pure + deterministic
 * given (payment, action, product, fields, fulfillment state).
 */
export function materializeDelivery(
  payment: Payment,
  action: DeliveryAction,
  product: Product,
  fields: Record<string, string>,
  state: FulfillmentState = { githubReady: false },
): DeliveredAccess[] {
  const entitlementId = entitlementIdForPayment(payment);

  // Invoices and payment requests deliver nothing but the settlement itself.
  if (product.metadata.kind === "invoice") {
    return [
      {
        kind: "saas_entitlement",
        title: product.name,
        value: "Paid",
        isLink: false,
        detail: "The seller has been notified. Your receipt PDF is available from the invoice link.",
      },
    ];
  }

  switch (action.type) {
    case "license_key_create":
      return [licenseKeyAccess(payment, product, entitlementId)];
    case "api_key_create":
      return [apiKeyAccess(payment, action, product, entitlementId)];
    case "file_access_grant":
      return [fileDownloadAccess(payment, action, product)];
    case "github_invite":
      return [githubInviteAccess(action, product, fields, state)];
    case "github_team_add":
      return [githubTeamAccess(action, fields, state)];
    case "discord_role_add":
      return [discordRoleAccess(action, fields, state)];
    default: {
      const accessUrl = sellerLink(product, "accessUrl");
      return [
        {
          kind: "saas_entitlement",
          title: product.name,
          value: accessUrl ?? "Access granted",
          isLink: accessUrl !== undefined,
          detail: accessUrl
            ? "Your access is active. Open the link and sign in with the email you used here."
            : "Your entitlement is active.",
        },
      ];
    }
  }
}

function licenseKeyAccess(
  payment: Payment,
  product: Product,
  entitlementId: string,
): DeliveredAccess {
  const machineLimit =
    typeof product.metadata.machineLimit === "number"
      ? product.metadata.machineLimit
      : 3;
  // Deterministic createdAt from payment so the key string is stable on refresh.
  const license = createLicenseKey(
    {
      organizationId: payment.organizationId,
      customerId: payment.customerId,
      productId: product.id,
      entitlementId,
      machineLimit,
    },
    new Date(payment.confirmedAt ?? payment.createdAt),
  );
  return {
    kind: "license_key",
    title: "License key",
    value: license.key,
    isLink: false,
    detail: `Activates on up to ${license.machineLimit} machine(s).`,
  };
}

function apiKeyAccess(
  payment: Payment,
  action: Extract<DeliveryAction, { type: "api_key_create" }>,
  product: Product,
  entitlementId: string,
): DeliveredAccess {
  const result = issueApiKey(
    {
      organizationId: payment.organizationId,
      customerId: payment.customerId,
      productId: product.id,
      entitlementId,
      scopes: action.scopes,
      env: "live",
    },
    new Date(payment.confirmedAt ?? payment.createdAt),
  );
  return {
    kind: "api_key",
    title: "API key",
    value: result.plaintext,
    isLink: false,
    detail: `Scopes: ${result.apiKey.scopes.join(", ")}. Store it now — it is shown only once.`,
  };
}

/** An https link stored on the product by the seller, or undefined. */
function sellerLink(product: Product, key: "fileUrl" | "accessUrl"): string | undefined {
  const value = product.metadata[key];
  return typeof value === "string" && value.startsWith("https://") ? value : undefined;
}

function fileDownloadAccess(
  payment: Payment,
  action: Extract<DeliveryAction, { type: "file_access_grant" }>,
  product: Product,
): DeliveredAccess {
  // A seller-hosted file (set in the dashboard) is revealed only after payment.
  const fileUrl = sellerLink(product, "fileUrl");
  if (fileUrl) {
    return {
      kind: "file_download",
      title: `Download — ${product.name}`,
      value: fileUrl,
      isLink: true,
      detail: "Your download link from the seller. Save it somewhere safe.",
    };
  }
  const url = generateSignedDownloadUrl({
    fileId: action.fileId,
    baseUrl: DEMO_DOWNLOAD_BASE,
    secret: DEMO_SECRET,
    expiresInSec: 7 * 24 * 60 * 60,
    maxDownloads: 5,
    downloadToken: derivedId("dl", payment.id),
    now: Math.floor(
      new Date(payment.confirmedAt ?? payment.createdAt).getTime() / 1000,
    ),
  });
  return {
    kind: "file_download",
    title: `Download — ${product.name}`,
    value: url,
    isLink: true,
    detail: "Signed link, valid for 7 days, up to 5 downloads.",
  };
}

/** Pending GitHub access: payment recorded, invite not (yet) sent. */
function githubPending(title: string, state: FulfillmentState): DeliveredAccess {
  return {
    kind: "github_invite",
    title,
    value: state.githubReady ? "Invite not sent yet" : "Pending setup",
    isLink: false,
    pending: true,
    detail: state.githubReady
      ? "Your payment is confirmed, but GitHub did not accept the invite. The merchant will resend it; no action is needed from you."
      : "Your payment is confirmed. The merchant has not finished connecting GitHub, so your invite will be sent once setup is complete.",
  };
}

function githubInviteAccess(
  action: Extract<DeliveryAction, { type: "github_invite" }>,
  product: Product,
  fields: Record<string, string>,
  state: FulfillmentState,
): DeliveredAccess {
  const title = "GitHub repository invite";
  const target = resolveRepoTarget(action.repoId, product);
  if (state.entitlement?.status !== "active" || !target) return githubPending(title, state);
  const username = fields.githubUsername ?? "";
  return {
    kind: "github_invite",
    title,
    value: `https://github.com/${target.owner}/${target.repo}/invitations`,
    isLink: true,
    detail: `Invite sent to @${username} for ${target.owner}/${target.repo} (${action.permission ?? "pull"}). Accept it from your GitHub notifications.`,
  };
}

function githubTeamAccess(
  action: Extract<DeliveryAction, { type: "github_team_add" }>,
  fields: Record<string, string>,
  state: FulfillmentState,
): DeliveredAccess {
  const title = "GitHub team access";
  if (state.entitlement?.status !== "active") return githubPending(title, state);
  const username = fields.githubUsername ?? "";
  return {
    kind: "github_invite",
    title,
    value: `https://github.com/orgs/${action.orgLogin}/teams/${action.teamSlug}`,
    isLink: true,
    detail: `@${username} added to ${action.orgLogin}/${action.teamSlug}.`,
  };
}

function discordRoleAccess(
  action: Extract<DeliveryAction, { type: "discord_role_add" }>,
  fields: Record<string, string>,
  state: FulfillmentState,
): DeliveredAccess {
  const who = fields.discordUsername ?? fields.discordUserId ?? "your account";
  if (state.entitlement?.status !== "active") {
    return {
      kind: "discord_role",
      title: "Discord role",
      value: state.discordReady ? "Role not granted yet" : "Pending setup",
      isLink: false,
      pending: true,
      detail: state.discordReady
        ? `Your payment is confirmed, but Discord did not accept the role for ${who} yet (join the server if you have not). It is retried automatically.`
        : "Your payment is confirmed. The seller has not finished connecting the Discord bot, so your role is granted as soon as setup is complete.",
    };
  }
  const [guildId] = (state.entitlement.resourceId ?? `${action.guildId}/`).split("/");
  return {
    kind: "discord_role",
    title: "Discord role granted",
    value: guildId ? `https://discord.com/channels/${guildId}` : "https://discord.com/channels/@me",
    isLink: true,
    detail: `The paid role was added to ${who}. Open the server in Discord to see the new channels.`,
  };
}

export { DEMO_ORG };
