/**
 * Delivery materialization.
 *
 * Given a confirmed payment + the product's delivery action + the buyer's
 * collected fields, produce the concrete access artifacts shown on the success
 * page. Every artifact is generated by a real @settlekit package function:
 *
 *  - license keys  -> @settlekit/license-keys createLicenseKey
 *  - api keys      -> @settlekit/api-keys issueApiKey
 *  - file download -> @settlekit/file-delivery generateSignedDownloadUrl
 *  - github invite -> @settlekit/common GitHub grant record + invite URL
 *  - discord role  -> @settlekit/common Discord role grant record
 *
 * These run server-side and are deterministic for a given session (so the
 * success page is stable on refresh): we derive entitlement ids and tokens
 * from the payment id rather than minting fresh random ids each render.
 */
import { createHmac } from "node:crypto";
import { createLicenseKey } from "@settlekit/license-keys";
import { issueApiKey } from "@settlekit/api-keys";
import { generateSignedDownloadUrl } from "@settlekit/file-delivery";
import type { DeliveryAction, Payment, Product } from "@settlekit/common";

import { DEMO_DOWNLOAD_BASE, DEMO_ORG, DEMO_SECRET } from "./seed";
import type { DeliveredAccess } from "./types";

/** Deterministic pseudo-id derived from a seed so renders are stable. */
function derivedId(prefix: string, seed: string): string {
  const hex = createHmac("sha256", DEMO_SECRET)
    .update(seed)
    .digest("hex")
    .slice(0, 24);
  return `${prefix}_${hex}`;
}

/**
 * Build the delivered access list for a confirmed payment. Pure + deterministic
 * given (payment, action, product, fields).
 */
export function materializeDelivery(
  payment: Payment,
  action: DeliveryAction,
  product: Product,
  fields: Record<string, string>,
): DeliveredAccess[] {
  const entitlementId = derivedId("ent", payment.id);

  switch (action.type) {
    case "license_key_create":
      return [licenseKeyAccess(payment, product, entitlementId)];
    case "api_key_create":
      return [apiKeyAccess(payment, action, product, entitlementId)];
    case "file_access_grant":
      return [fileDownloadAccess(payment, action, product)];
    case "github_invite":
      return [githubInviteAccess(action, product, fields)];
    case "github_team_add":
      return [githubTeamAccess(action, fields)];
    case "discord_role_add":
      return [discordRoleAccess(action, fields)];
    default:
      return [
        {
          kind: "saas_entitlement",
          title: product.name,
          value: "Access granted",
          isLink: false,
          detail: "Your entitlement is active.",
        },
      ];
  }
}

function licenseKeyAccess(
  payment: Payment,
  product: Product,
  entitlementId: string,
): DeliveredAccess {
  const machineLimit =
    typeof product.metadata.machineLimit === "number"
      ? product.metadata.machineLimit
      : 3;
  // Deterministic createdAt from payment so the key string is stable on refresh.
  const license = createLicenseKey(
    {
      organizationId: payment.organizationId,
      customerId: payment.customerId,
      productId: product.id,
      entitlementId,
      machineLimit,
    },
    new Date(payment.confirmedAt ?? payment.createdAt),
  );
  return {
    kind: "license_key",
    title: "License key",
    value: license.key,
    isLink: false,
    detail: `Activates on up to ${license.machineLimit} machine(s).`,
  };
}

function apiKeyAccess(
  payment: Payment,
  action: Extract<DeliveryAction, { type: "api_key_create" }>,
  product: Product,
  entitlementId: string,
): DeliveredAccess {
  const result = issueApiKey(
    {
      organizationId: payment.organizationId,
      customerId: payment.customerId,
      productId: product.id,
      entitlementId,
      scopes: action.scopes,
      env: "live",
    },
    new Date(payment.confirmedAt ?? payment.createdAt),
  );
  return {
    kind: "api_key",
    title: "API key",
    value: result.plaintext,
    isLink: false,
    detail: `Scopes: ${result.apiKey.scopes.join(", ")}. Store it now — it is shown only once.`,
  };
}

function fileDownloadAccess(
  payment: Payment,
  action: Extract<DeliveryAction, { type: "file_access_grant" }>,
  product: Product,
): DeliveredAccess {
  const url = generateSignedDownloadUrl({
    fileId: action.fileId,
    baseUrl: DEMO_DOWNLOAD_BASE,
    secret: DEMO_SECRET,
    expiresInSec: 7 * 24 * 60 * 60,
    maxDownloads: 5,
    downloadToken: derivedId("dl", payment.id),
    now: Math.floor(
      new Date(payment.confirmedAt ?? payment.createdAt).getTime() / 1000,
    ),
  });
  return {
    kind: "file_download",
    title: `Download — ${product.name}`,
    value: url,
    isLink: true,
    detail: "Signed link, valid for 7 days, up to 5 downloads.",
  };
}

function githubInviteAccess(
  action: Extract<DeliveryAction, { type: "github_invite" }>,
  product: Product,
  fields: Record<string, string>,
): DeliveredAccess {
  const username = fields.githubUsername ?? "";
  const [owner, repo] = parseRepo(action.repoId, product);
  return {
    kind: "github_invite",
    title: "GitHub repository invite",
    value: `https://github.com/${owner}/${repo}/invitations`,
    isLink: true,
    detail: `Invite sent to @${username} for ${owner}/${repo} (${action.permission ?? "pull"}). Accept it from your GitHub notifications.`,
  };
}

function githubTeamAccess(
  action: Extract<DeliveryAction, { type: "github_team_add" }>,
  fields: Record<string, string>,
): DeliveredAccess {
  const username = fields.githubUsername ?? "";
  return {
    kind: "github_invite",
    title: "GitHub team access",
    value: `https://github.com/orgs/${action.orgLogin}/teams/${action.teamSlug}`,
    isLink: true,
    detail: `@${username} added to ${action.orgLogin}/${action.teamSlug}.`,
  };
}

function discordRoleAccess(
  action: Extract<DeliveryAction, { type: "discord_role_add" }>,
  fields: Record<string, string>,
): DeliveredAccess {
  const userId = fields.discordUserId ?? "";
  return {
    kind: "discord_role",
    title: "Discord role granted",
    value: "https://discord.com/channels/@me",
    isLink: true,
    detail: `Role ${action.roleId} granted to user ${userId} in guild ${action.guildId}. Open Discord to see the new channels.`,
  };
}

/** Resolve repo owner/name from the action's repoId or product metadata. */
function parseRepo(repoId: string, product: Product): [string, string] {
  if (repoId.includes("/")) {
    const [owner, repo] = repoId.split("/");
    return [owner ?? "owner", repo ?? "repo"];
  }
  const owner =
    typeof product.metadata.repoOwner === "string"
      ? product.metadata.repoOwner
      : "owner";
  const repo =
    typeof product.metadata.repoName === "string"
      ? product.metadata.repoName
      : repoId;
  return [owner, repo];
}

export { DEMO_ORG };
